ARG ELASTIC_STACK_VERSION=8.14.3
FROM docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_STACK_VERSION}

LABEL maintainer="Tan Nguyen <tannp@cslant.com>"
LABEL authors="cslant"
LABEL description="Elasticsearch image for CSlant development"
